---
- include: "ganomede-build-image.yml"
  when: (definitions[name].build_image | default(False))

- name: "Deploying ganomede.{{ name }}"
  hosts: marathon-api-server
  gather_facts: no
  tags: [ "ganomede", "marathon", "ganomede_{{ name | mandatory }}" ]

  vars:

    app_name: "{{ config.app_name }}/ganomede/{{ name }}"
    dns_domain: "{{ config.app_name.split('/') | reverse | join('.') }}.marathon.mesos"
    redis_proxy_host: "redis-proxy.redis.{{ dns_domain }}"
    couchdb_proxy_host: "couchdb-proxy.{{ dns_domain }}"
    marathon_wait_for_deployment: False

    service_labels: "{{ definitions[name].labels | default({}) }}"
    default_labels:
      HAPROXY_GROUP: "external"
      HAPROXY_0_PATH: "/{{ name }}/v1"
      HAPROXY_0_VHOST: "{{ config.vhost|string }}"

    service_env: "{{ definitions[name].env | default({}) }}"
    service_build: "{{ definitions[name].build_image | default(False) }}"
    service_image: "{{ definitions[name].image | default((service_build | ternary('ganomede-', 'ganomede/')) + name) }}"
    service_version: "{{ config.ganomede[name].version | default(definitions[name].version) }}"

  roles:
  - role: topface.marathon_app
    marathon_url: http://{{ inventory_hostname }}:8080
    marathon_app:
      id: /{{ app_name }}
      container:
        type: DOCKER
        docker:
          image: "{{ service_image }}:{{ service_version }}"
          network: BRIDGE
          portMappings:
            - containerPort: 8000
              hostPort: 0
              servicePort: "{{ config.ganomede[name].port }}"
              protocol: tcp
      env: "{{ shared_env | combine(service_env) }}"
      instances: "{{ config.ganomede[name].instances | default(1) }}"
      cpus: "{{ config.ganomede[name].cpus | default(0.5) }}"
      mem: "{{ config.ganomede[name].mem | default(512) }}"
      labels: "{{ default_labels | combine(service_labels) }}"
      ports:
        - 0
      healthChecks:
        - protocol: HTTP
          path: /{{ name }}/v1/ping/_health_check
          portIndex: 0
          gracePeriodSeconds: 60
          maxConsecutiveFailures: 3
          intervalSeconds: 5
          timeoutSeconds: 5

