---
- name: "Deploying couchdb.{{ index }}"
  hosts: marathon-api-server
  gather_facts: no

  vars:
    app_name: "{{ config.app_name }}/couchdb"
    dns_domain: "{{ config.app_name.split('/') | reverse | join('.') }}.marathon.mesos"
    marathon_wait_for_deployment: False

    # index of the server to act on (0 or 1).
    # aimed at being specified on the command line.
    index: -1

    couchdb_host: "{{ (config.couchdb.hosts | default(['host0','host1']))[index|int] }}"
    couchdb_database_prefix: "{{ config.app_name.split('/') | join('-') }}-"

    marathon_app_id: "/{{ app_name }}-{{ index }}"

  pre_tasks:
    - debug: msg="Launching couchdb-{{ index }}"
    - fail: msg="Please specify the index(0 or 1) with \"-e index=0\""
      when: (index|int) < 0 or (index|int) > 1
      tags: [ 'couchdb' ]

  roles:
  - role: topface.marathon_app
    tags: [ 'marathon', 'couchdb' ]
    marathon_url: http://{{ inventory_hostname }}:8080
    marathon_app:
      id: "{{ marathon_app_id }}"
      container:
        type: DOCKER
        docker:
          image: apache/couchdb:1.7.1
          network: HOST
        volumes:
          - containerPath: /usr/local/var/lib/couchdb
            hostPath: /usr/local/{{ cluster_name }}/{{ app_name }}
            mode: RW
      env:
        COUCHDB_HTTP_PORT: "{{ config.couchdb.port }}"
        COUCHDB_HTTP_BIND_ADDRESS: "{{ hostvars[couchdb_host].tun0 }}"
      instances: 1
      cpus: "{{ config.couchdb.cpus | default(0.1) }}"
      mem: "{{ config.couchdb.mem | default(256) }}"
      healthChecks:
        - protocol: HTTP
          port: "{{ config.couchdb.port }}"
          path: /
          gracePeriodSeconds: 120
          maxConsecutiveFailures: 3
          intervalSeconds: 20
          timeoutSeconds: 20
      constraints:
        - [ "hostname", "CLUSTER", "{{ couchdb_host }}" ]

      # Only one instance of CouchDB should run at any point in time.
      upgradeStrategy:
        minimumHealthCapacity: 0
        maximumOverCapacity: 0

